import type { Metadata } from "next";
import domenFavicon from "../../assets/domen-favicon.ico";
import "./globals.css";
import SmoothScroll from "./smooth-scroll";
import SiteLoader from "./site-loader";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: domenFavicon.src,
  },
};

export default function RootLayout({ children }: LayoutProps<"/">) {
  return (
    <html
      lang="en"
      className="h-full antialiased"
    >
      <body className="min-h-full flex flex-col">
        <SiteLoader />
        <SmoothScroll>{children}</SmoothScroll>
      </body>
    </html>
  );
}
